### ISSUE TITLE
Explain @setting arguments in wiki

### ISSUE THREAD

**Issue by DanielSank** [labrad/pylabrad#127]
See [here](https://github.com/labrad/pylabrad/wiki/Writing-Servers). It would be nice if someone could take a quick look and make sure I didn't say anything false. I'm not trying to make this the main documentation because I think that should be in the code, but this came up with a new user so I thought it should be in the wiki.

Will close issue once someone indicates that the entry is ok (we don't have a good workflow for the wikis yet).

**Comment by maffoo** [comment]
There's a lot of duplication between the first segment with the bulleted list (which it looks like you added) and the later 'Setting Decorator' section. We should clean that up.

In addition, I would add that if you omit an explicit type for any particular arg and/or for returns, then the type will be '?', that is, we will accept any type for that argument, and allow any type to be returned (at least any type that can be flattened to labrad data).

**Comment by maffoo** [comment]
Otherwise, LGTM.

**Comment by DanielSank** [comment]
@maffoo Fixed. Take a quick look?

**Comment by maffoo** [comment]
LGTM
