### ISSUE TITLE
copy.deepcopy of a WithUnit instance

### ISSUE THREAD

**Issue by jayich** [labrad/pylabrad#128]
Is it expected behavior that a WithUnit instance can't be deepcopied?  I would like to make a deepcopy of an object that contains some WithUnit instances.  Running in IPython I get the following:

```python
>>> import copy as _copy
>>> from labrad.units import WithUnit
>>> a = WithUnit(56., 's')
>>> b = _copy.deepcopy(a)
...
...
TypeError: _init() takes at least 4 arguments (1 given)
```

**Comment by ejeffrey** [comment]
copy and deepcopy should work.  For Value and Complex types, they should
simply return self.  ValueArrays should return a copy.  What version of
pylabrad are you using?

**Comment by ejeffrey** [comment]
Yeah, it works for me with current version of pylabrad

In [1]: import labrad.units as U
In [2]: import copy
In [3]: copy.deepcopy(4*U.s)
Out[3]: Value(4.0, 's')

**Comment by jayich** [comment]
Sorry, I was not up-to-date.  I'm very happy that I can deepcopy.
