### ISSUE TITLE
Any reason not to install with setuptools?

### ISSUE THREAD

**Issue by chrismacklin** [labrad/pylabrad#132]
As far as I can tell, installation seems to work fine with setuptools, and allows use of the nice ```python setup.py develop``` command.  I probably haven't exercised all of the features of LabRAD, though; does anyone know if there is a reason to prefer distutils for installing pylabrad?

**Comment by DanielSank** [comment]
This is probably a StackOverflow post somewhere.

**Comment by chrismacklin** [comment]
Are there instructions somewhere for executing the labrad test suite?  I tried running it with nose but clearly more configuration needs to take place than is happening.

**Comment by DanielSank** [comment]
With pytest installed in your virtualenv run `py.test` in the root directory.

**Comment by chrismacklin** [comment]
This is dumb and aimless issue, I'm going to close it now.
