### ISSUE TITLE
Wiki/Clients - Defining cxn

### ISSUE THREAD

**Issue by jwenner** [labrad/pylabrad#136]
On the "Wiki/Writing Clients" page, it is described to connect to labrad via `cxn=labrad.connect()`. Shouldn't there be a note about using `with labrad.connect() as cxn` instead in scripts to avoid a connection zoo?

(Note that someone else will have to make this change; I don't seem to have edit access.)

**Comment by maffoo** [comment]
I just invited you to be a contributor, @jwenner; once you get that, please feel free to edit the wiki.

**Comment by DanielSank** [comment]
Actually I'm already writing this up.

**Comment by DanielSank** [comment]
[Done](https://github.com/labrad/pylabrad/wiki/Writing-clients).
