### ISSUE TITLE
Programmatically start/stop servers for unit tests?

### ISSUE THREAD

**Issue by chrismacklin** [labrad/pylabrad#148]
Is there a recommended way to start and stop servers programmatically to ensure that test suites do not require manually launching servers?

```test_refresh.py``` makes a call to ```util.syncRunServer(...server...)``` which seems fine to me, but I don't understand the implications of "Run a labrad server of the specified class in a synchronous context." from the doc for this function.

**Comment by maffoo** [comment]
Running a server "in a synchronous context" means that your main code is synchronous (not driven by the twisted reactor) as it is in standard unit tests. the `util.syncRunServer` function was written for the purpose you describe, to spin up a server when running tests, so it'd be the recommended way. If you'd like to rework some of the old tests that currently assume a test server is running to use this mechanism, that'd be great. They'll still require a labrad manager to be running, of course, so they're not true "unit tests", more like "integration tests", but certainly such a change would make running the tests easier.

**Comment by chrismacklin** [comment]
I'm mostly interested in this for testing my own servers, but sure PR incoming as an exercise.
