### ISSUE TITLE
node should store log messages emitted by running servers

### ISSUE THREAD

**Issue by maffoo** [labrad/pylabrad#156]
Currently, output emitted by node-launched servers (e.g. stuff they write to stdout and stderr) gets captured by the node in a rolling buffer so you can look at the last few lines of output, but otherwise it just goes into the ether. We should set things up to actually save this output so that we can use it for debugging issues, etc.

**Comment by pomalley** [comment]
+1

**Comment by DanielSank** [comment]
Yay logging!

**Comment by ejeffrey** [comment]
On linux we could do this via syslog.

**Comment by DanielSank** [comment]
> On linux

Are we *sure* VISA is a no-go on Linux?

**Comment by ejeffrey** [comment]
We aren't sure, I am hoping it works.  Will be trying it out this week or
so.

**Comment by pomalley** [comment]
I was totally unable to get visa to work on ubuntu (spent a couple hours on
it, even had brooks contact someone at NI). Would be great to hear
otherwise.
