### ISSUE TITLE
tab completion not showing labrad servers on Windows

### ISSUE THREAD

**Issue by jayich** [labrad/pylabrad#167]
Has anyone else seen the following behavior on a Windows machine?

When using an IPython (4.0.1) shell and pylabrad (0.93.1) I run the following

```
>>> import labrad
>>> cxn = labrad.connect()
>>> cxn.
```
Then running tab completion I do not see any of my servers.

```
>>> cxn. servers
```
Provides a list of all my servers.

On a different Windows machine with IPython (3.2.0) I can see the servers.

**Comment by maffoo** [comment]
The connection object implements a method called `_getAttributeNames` that returns a list of dynamic attribute names for tab completion. I think this name was defined by a really old python interactive shell called pycrust, so various projects used it and ipython thus also invoked that method when attempting tab-completion. I presume support for this has been removed from IPython 4, though I haven't found this documented anywhere. It looks like we probably need to implement a method called `__dir__` instead (the 3.2.1 docs describe this [here](https://ipython.org/ipython-doc/3/config/integrating.html); I presume that's more standard and will still work in ipython 4).

**Comment by ejeffrey** [comment]
We just noticed this recently on ipython 4.  Not sure what the problem is
yet.
