### ISSUE TITLE
None and units

### ISSUE THREAD

**Issue by zchen088** [labrad/pylabrad#183]
When I multiply a unit by ```None```, I get the unit back. Is this intended behavior?

**Comment by DanielSank** [comment]
For example
```python
>>> import labrad.units as units
>>> None * units.Unit('MHz')
<Unit 'MHz'>
```

**Comment by maffoo** [comment]
I think that is vestigial behavior from the olden days when you could have `Value(1, None)` which was different from `Value(1, '')`. In the former case the actual `unit` attribute would have been `None` and I guess the unit multiplication included the logic to handle that case. Clearly we can get rid of this now and throw a TypeError as you suggest.
