### ISSUE TITLE
Unable to connect from other computers

### ISSUE THREAD

**Issue by jwenner** [labrad/pylabrad#186]
When I try to call `labrad.connect()` from a computer besides the manager computer, I get a `Connection lost.` message. Running current master of pylabrad on client computer. Running scalabrad 0.5.1 on server computer using shortcut target `"C:\Program Files\Java\jre1.8.0_65\bin\java.exe" -cp lib/* org.labrad.manager.Manager --registry=file:///R:/_LabRADRegistry_/?format=delphi --tls-required=false`. Error stack trace below:

```
Python 2.7.9 (default, Dec 10 2014, 12:24:55) [MSC v.1500 32 bit (Intel)]
Type "copyright", "credits" or "license" for more information.

IPython 2.1.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: import labrad

In [2]: cxn=labrad.connect()
STARTTLS failed due to untrusted server certificate:
SHA1 Fingerprint=DF:CC:5A:B6:88:13:5E:D3:8B:6C:78:68:93:41:37:7A:3C:DC:E4:71

Accept server certificate for host 'trench'? (accept just this [O]nce; [S]ave an
d always accept this cert; [R]eject) s
---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
<ipython-input-2-6470a6c14392> in <module>()
----> 1 cxn=labrad.connect()

C:\pylabrad\labrad\__init__.pyc in connect(host, port, name, **kw)
     26 def connect(host=constants.MANAGER_HOST, port=None, name=None, **kw):
     27     """Create a client connection to the labrad manager."""
---> 28     cxn = backend.connect(host=host, port=port, name=name, **kw)
     29     return client.Client(cxn)
     30

C:\pylabrad\labrad\backend.pyc in connect(host, port, name, backend, **kw)
    428             backend = 'asyncore'
    429     cxn = backends[backend](name)
--> 430     cxn.connect(host, port, **kw)
    431     return cxn
    432

C:\pylabrad\labrad\backend.pyc in connect(self, host, port, timeout, password, t
ls)
     34         self.host = host
     35         self.port = port
---> 36         self.ID = self._connect(password, timeout, tls=tls)
     37         self.connected = True
     38

C:\pylabrad\labrad\backend.pyc in _connect(self, password, _timeout, tls)
     64             startReactor()
     65             self.cxn = self.call(getConnection, self.host, self.port, se
lf.name,
---> 66                                  password, tls=tls).wait()
     67             return self.cxn.ID
     68

C:\pylabrad\labrad\backend.pyc in wait(self)
    405                 # If any Future in the queue fails,
    406                 # we immediately bail.
--> 407                 result.raiseException()
    408             else:
    409                 for func, args, kw in f.callbacks:

C:\Python27\lib\site-packages\twisted\python\failure.pyc in raiseException(self)


Exception: Connection lost.

In [3]:
```

**Comment by jwenner** [comment]
Note that if I call `labrad.connect(tls='off')`, it works. However, as `labrad.connect()` is used throughout pyle, this is not a suitable solution.

**Comment by maffoo** [comment]
@jwenner, I'm guessing this is a problem with the TLS host configuration of the manager. By default it starts with a certificate with a hostname of 'localhost', and you're trying to validate that against the hostname you connected to, say 'trench.physics.ucsb.edu', so the validation fails. I just pushed a change in scalabrad that will include a certificate bound to the machine hostname in the default TLS config for the manager, but until that is out, you should explicitly specify the `--tls-hosts` command line parameter for the manager and include all the hostnames that might be used when connecting to that manager, e.g. `--tls-hosts=trench.physics.ucsb.edu;trench.gigabit;trench`. Please try restarting the manager with that change and let me know if that fixes the issue.

As for the unhelpful error message, I'll look into whether it's possible to get more information when the cert validation fails.

**Comment by jwenner** [comment]
@maffoo, restarting the manager with the change you suggested (i.e., specifying `--tls-hosts` as you indicate) indeed works. Thanks!
