### ISSUE TITLE
Print server output when run directly but not in node

### ISSUE THREAD

**Issue by jwenner** [labrad/pylabrad#191]
For a server, is it possible to print output to the screen when the server is run directly but not to print the output when run in the node? I'd like to do this to enable server diagnosis, but the print output could be too much for the node. (See martinisgroup/servers#255 for context.)

Note that both logging and sys.stderr/stdout seem to print to both the node and the screen.

**Comment by ejeffrey** [comment]
Hi Jim,

Can you be more specific about "too much for the node"?  We probably should do a better job of log management from the node, but I don't think it should be overwhelmed by the stuff you are talking about.

**Comment by jwenner** [comment]
During certain cases of normal operation, there could be messages resulting from the mks server change every second or so. This is because, during a cooldown, some of the pressures (i.e., the still and likely the low-pressure pot) are >10torr and so are out of range.

**Comment by ejeffrey** [comment]
I don't think a message every second should be a problem, and if it is, I
would like to fix that.

Nevertheless, generating 50,000 'overpressure' warnings in a row is
probably not useful.  The typical way to fix this is to display the warning
only once, and then remember that the gauge is out-of-range and not display
another error until it is back in range.

**Comment by DanielSank** [comment]
> Nevertheless, generating 50,000 'overpressure' warnings in a row is
probably not useful.  The typical way to fix this is to display the warning
only once, and then remember that the gauge is out-of-range and not display
another error until it is back in range.

+1

**Comment by ejeffrey** [comment]
I am closing this, I don't think we need this feature, but I would happy to review a change to the mks_server to group out-of-range errors.
