### ISSUE TITLE
Enable node to show running servers started independently of itself

### ISSUE THREAD

**Issue by DanielSank** [labrad/pylabrad#193]
It would be nice for the node to subscribe to whatever messages are needed such that it would know about servers started independently of itself. I suppose it might be a bit of work to enable it to *stop* servers it didn't start, but just showing running servers as running would be great.

**Comment by maffoo** [comment]
The scalabrad-web interface shows all servers that are running, regardless of whether they were started by the node or not. It's a different screen than the node interfaces, but the information is there. Where would you want to surface this information?

**Comment by DanielSank** [comment]
This is definitely the wrong place for this issue. Sorry.
