### ISSUE TITLE
tab-completion of dynamic attributes is broken in iPython 4.0

### ISSUE THREAD

**Issue by chrismacklin** [labrad/pylabrad#197]
Probably due to the totally undocumented (and likely deprecated and now removed) mechanism that pylabrad uses to expose the dynamic attributes (```_getAttributeNames```).

**Comment by DanielSank** [comment]
Didn't someone address this a couple weeks ago?

**Comment by maffoo** [comment]
Yeah, this is fixed in master.

**Comment by ejeffrey** [comment]
#168 is the PR that fixed this

**Comment by chrismacklin** [comment]
Great!  (Already) closed by #168
