### ISSUE TITLE
Recommended method to round WithUnit instances?

### ISSUE THREAD

**Issue by jayich** [labrad/pylabrad#201]
For hardware related tests to be cross computer compatible I am would like to round WithUnit instances.  Is there a recommended way to perform this rounding operation?

**Comment by maffoo** [comment]
You probably want to get the numeric value expressed in a particular unit, then round or do whatever operation on the value, then tack the units back on, so something like:
```
round(x[unit])*unit
```
where `unit` is a `Unit` object.

**Comment by jayich** [comment]
Thank you @maffoo
