### ISSUE TITLE
old pylabrad files on sourceforge

### ISSUE THREAD

**Issue by jayich** [labrad/pylabrad#206]
pylabrad code is hosted here:

http://sourceforge.net/projects/pylabrad/files/pylabrad/

It is probably best to redirect to GitHub. It is possibly a good idea to remove the hosted versions of pylabrad on sourceforge.

**Comment by jwenner** [comment]
@maffoo 

In addition, should we migrate any of the old Sourceforge wiki over here (as noted in #98), or is it all so antiquated that it is useless? I suspect that the tutorial (http://sourceforge.net/p/pylabrad/wiki/MainTutorial/) would probably fail as the fractal server no longer exists, but maybe something might still be reasonable to port over?

**Comment by maffoo** [comment]
I added links on the sourceforge page to the github project for development and PyPI for packages. I also removed the files for download and the code repos from the sourceforge page.

**Comment by maffoo** [comment]
As for the wiki, the info from the main page has been moved to the github wiki: https://github.com/labrad/pylabrad/wiki. The tutorial series does indeed seem rather out of date, so I don't think we need to migrate that, but we should continue to improve the docs here. I'll leave that to do as part of #98.
