### ISSUE TITLE
pylabrad modules on sourceforge

### ISSUE THREAD

**Issue by jayich** [labrad/pylabrad#207]
Similar to issue https://github.com/labrad/pylabrad/issues/206, I wanted to make sure that the appropriate people are aware of likely old modules hosted on sourceforge here:

http://sourceforge.net/projects/labradmodules/

Redirection is probably appropriate here as well.

**Comment by maffoo** [comment]
I added a link on the sourceforge page to direct people to the martinisgroup/servers repo, where current server development is happening.
