### ISSUE TITLE
Environment variable documentation

### ISSUE THREAD

**Issue by jayich** [labrad/pylabrad#209]
I could not find documentation of labrad's environment variables.  A handful are mentioned on "The Node" page of this wiki.  This wiki might be a good place to document them all in one place.  I have copied and pasted our lab's notes on labrad's environment variables for starters:

These are system variables that you need to set.
LABRADNODE - this gives the node name of the computer
LABRADPASSWORD - the password to logon to labrad. Always used "lab" for the password, this is not a real layer of security. That is higher up.
LABRADPORT - We think this is always 7682. This is hardcoded into labrad, from what we can tell.
LABRADHOST - which computer labrad connects to. For default use 'localhost', if you want one computer in a network to run an experiment use this control computer's IP address. IP addresses need to be hardcoded.
This is new: LABRAD_TLS - 'off'. Not sure about this one yet. The molecules set it to off for the client computers.

**Comment by maffoo** [comment]
Thanks for the idea to document these better, @jayich. I'll add a wiki page. I should note that LABRADPORT, LABRADHOST and LABRAD_TLS all have default values. These really only need to be set if you want to override the defaults, and of course they need to correspond to what the manager is expecting.

**Comment by maffoo** [comment]
Added wiki page: https://github.com/labrad/pylabrad/wiki/Configuration

**Comment by jayich** [comment]
@maffoo , the wiki page looks great.  Perhaps include LABRADNODE as well.

**Comment by maffoo** [comment]
done.
