### ISSUE TITLE
which labrad?

### ISSUE THREAD

**Issue by jayich** [labrad/pylabrad#221]
@maffoo ,  we have been happily running Delphi labrad 1.1.3.  But, which labrad should we be using?  I have noticed a lot of scala development but I'm not paying close attention.  I like to keep our code as up-to-date as possible, etc.

**Comment by maffoo** [comment]
scalabrad is where all the new development is happening on the manager. The big change is TLS support, but there are lots of little fixes as well, and the threading model is much better so we see greatly increased throughput, which may or may not be important for your workloads. The scala manager doesn't have the graphical interface of the delphi manager, so it's not quite as easy to just get up and running; we need to do some work on that front. But it'd be great if you would like to try it out and I'm happy to help with that.

**Comment by maffoo** [comment]
As to what you "should" be using, whatever works best for you is always the answer :)

**Comment by ejeffrey** [comment]
The delphi manager should still work, but scalabrad will likely have better
performance in some cases, and is where new features (i.e., SSL/TLS
support) will be developed.  That comes with a couple of caveats:

1) The manager has no GUI, it runs in the background/console and you need
to manage it via the web interface.
2) Named signals are now case sensitive.  That has almost no implications
except that you need to update the registry editor binary.
3) scalabrad doesn't have the whitelist/blacklist feature.  This avoids the
common frustration of managing the whitelist, but if you want to control
access you need to use the OS firewall feature.
4) The OS firewall feature in windows is pretty annoying.  In particular,
it has one set of rules for "java" which applies to all java applications.
So if you have ever blocked network access for java, you will have to undo
it.

If you don't want to use TLS, I don't think it matters much which version
you are using yet.

**Comment by jayich** [comment]
This is informative, thank you both.  Is there documentation for setting up and running the scala manager?  If there is not I could post questions here or on the scalabrad issues page.  I find all of these little fixes culminate in significant user experience improvements.  Basic question:  can one seamless switch back and forth between managers (in case the scala setup is not complete)?

Note: it might be a bit before I start working on setting up scalabrad.

Regarding what works best: In general I find that long term it is always best if I keep up with general Martinis lab use cases and practices.  If you guys are all using scalabrad I am heavly inclined to swtich.

**Comment by maffoo** [comment]
There is some documentation on the scalabrad repo [README](https://github.com/labrad/scalabrad#running-scalabrad). I'd suggest creating issues there rather than here, but of course we can move issues around as needed. It should be possible to move back and forth between the two managers so you can try things out; the scala manager uses environment variables or command line flags for configuration, and you can see documentation by invoking it with the `--help` option. For example, you'll want to configure scalabrad to point to your existing registry directory on disk and use the delphi registry format.
