### ISSUE TITLE
importing labrad throws error on line from concurrent.futures import Future

### ISSUE THREAD

**Issue by thchwhite** [labrad/pylabrad#228]
Apparently this file doesn't exist in pylabrad or as part of the standard python install

**Comment by maffoo** [comment]
If you use pip to install the latest version of pylabrad, it should pull down the library. Otherwise, just run `pip install futures` to get it.

**Comment by thchwhite** [comment]
this was the issue, thanks.

**Comment by maffoo** [comment]
@thchwhite, can we close this?

**Comment by thchwhite** [comment]
Sure,  I'll close it now
