### ISSUE TITLE
Setting decorator changes break Signals

### ISSUE THREAD

**Issue by maffoo** [labrad/pylabrad#244]
Recent changes to the way the setting decorator works break the [Signal](https://github.com/labrad/pylabrad/blob/master/labrad/server.py#L37) object, which is used as a way to notify clients of changes in a server and also creates a setting that clients call to register to receive notifications, or to stop receiving them. The main place this is used is in the data vault, but that's an important one.

**Comment by jayich** [comment]
I just wanted to comment that signals are important for a number of servers we run.    If there is anything that I can do to help improve Signal I am more than happy to contribute.  I'll track this issue and at least try and help with documentation, for example.

**Comment by ejeffrey** [comment]
Thanks for the input andrew,

I think the biggest problem is specific to the multi-headed datavault where
there are multiple instances of the server object, one per connection. The
issue is whether the signal object is per class or per instance, i.e.:

```
class MyServer(LabradServer):
    def __init__(self, ...)::
        self.instance_signal = Signal(...)
    class_signal = Sigal(...)

The way I tried to change the @setting decorator, the former doesn't work,
since it is based on the descriptor protocol.  The latter is what I would
prefer but I think it doesn't work for multi-headed servers since the
setting state would get shared between instances.



On Wed, Apr 20, 2016 at 11:28 AM, jayich <notifications@github.com> wrote:

> I just wanted to comment that signals are important for a number of
> servers we run. If there is anything that I can do to help improve Signal I
> am more than happy to contribute. I'll track this issue and at least try
> and help with documentation, for example.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/labrad/pylabrad/issues/244#issuecomment-212546487>
>
