### ISSUE TITLE
Twisted warning when I don't have `service_identity`

### ISSUE THREAD

**Issue by pomalley** [labrad/pylabrad#253]
I recently (finally) updated my pylabrad and got this warning on import:

```
:0: UserWarning: You do not have a working installation of the service_identity module: 'No module named service_identity'.  Please install it from <https://pypi.python.org/pypi/service_identity> and make sure all of its dependencies are satisfied.  Without the service_identity module and a recent enough pyOpenSSL to support it, Twisted can perform only rudimentary TLS client hostname verification.  Many valid certificate/hostname mappings may be rejected.
```

Easily fixed with `pip install service_identity`; is this something we care about?

(On Windows 10, btw.)

**Comment by maffoo** [comment]
It's a good idea to have this; always best to keep TLS as up to date as possible. We can add it to the requirements file so you get it by default when installing pylabrad.

Out of curiosity, are you putting the pylabrad source on your python path or are you pip installing it from pypi?

**Comment by pomalley** [comment]
Made a PR for it: #254.

I have pylabrad on my python path. I reinstalled all the python on my windows machine and ended up going the Anaconda route; seems to have worked out pretty well so far (integrates perfectly with pip, etc).
