### ISSUE TITLE
Multiple nodes on one host

### ISSUE THREAD

**Issue by aransfor** [labrad/pylabrad#255]
We use servers from a few groups(Haeffner Riken Martinis and Campbell). We run into node naming conflicts for some servers (data vault, serial server etc.) Is there a way to have a node for each repository so we can cherry pick servers from each?

**Comment by maffoo** [comment]
You certainly can do this, just launch multiple copies of the node server with different names:
```
$ python -m labrad.node --name=node1 &
$ python -m labrad.node --name=node2 &
```
and then configure them to look in different directories for servers to run.

Note that the latest version of the node can handle multiple versions of a server with a given name on its search path. It will display all such servers in the list of servers to be launched, with the version number added in to disambiguate the names. That may do what you want without having to launch multiple nodes (and if you have different "versions" of the same server in different repositories that have the same number, then you should bug the repository owners to change the version numbers when they make changes to the servers :) ).

**Comment by aransfor** [comment]
@maffoo excellent answer. As usual you guys have been a huge help
