### ISSUE TITLE
Can only connect with backend='asyncore'

### ISSUE THREAD

**Issue by edowd** [labrad/pylabrad#281]
Hi, I'm new to LabRAD and just trying to get set up for the first time. I have installed the LabRAD manager and explorer and installed pylabrad using pip install, but when I try to open a connection using labrad.connect() I get the error "Exception: Connection lost." It does work, however, if I use labrad.connect(backend = 'asyncore'). Any idea what the problem could be? Thanks much!

**Comment by DanielSank** [comment]
You say you installed the manager and explorer. Where did those come from? The sourceforge stuff is super old and no longer maintained. Please use the manager found [here](https://github.com/labrad/scalabrad).

**Comment by edowd** [comment]
aha! That made a difference. Thanks.

**Comment by maffoo** [comment]
Closing for now; @edowd, please reopen or create a new issue if you have other problems.
