### ISSUE TITLE
Trouble understanding how to use the node

### ISSUE THREAD

**Issue by edowd** [labrad/pylabrad#284]
Hi - I'm just starting with labrad and am having trouble with the node. I have the node up and running (I used python -m labrad.node) but can't figure out how to add servers to the list that the node starts up. Currently there are no servers listed as available servers for the node, even if they are serving. How do I point the node to the folder where my servers are stored? Thanks.

**Comment by jwenner** [comment]
There are several registry keys which need to be set. Could you please take a look at the [node docstring](https://github.com/labrad/pylabrad/blob/master/labrad/node/__init__.py) and see if this is clear?

In addition to the registry keys indicated there (`autostart`, `directories`, `extensions`), you may also need the key `javapath` if you are using any servers based on java or scala. On Windows at least, the value should be a string with the directory of your Java VM (e.g., `"C:\\Java\\jre1.7.0\\bin\\java.exe"`).

Please let me know if you still are unsure about how to configure this.

**Comment by edowd** [comment]
Thanks. I couldn't figure out how to set the registry keys from command line. I got scalabrad-web set up and now I am in pretty good shape with the node I think.
