### ISSUE TITLE
Can clients be disconnected from the scalabrad manager web interface?

### ISSUE THREAD

**Issue by jayich** [labrad/pylabrad#286]

**Comment by jayich** [comment]
If so, how?

With the delphi manager you could click on a client and then click disconnect.

**Comment by jwenner** [comment]
I think that a similar functionality has been introduced in the most recent release of scalabrad-web (v2.0), and in particular in labrad/scalabrad-web#248. However, as I'm still on v1.1.0, I can't say for certain that this functionality works...

**Comment by jayich** [comment]
@jwenner , thank you.  I'm looking forward to trying this out.
