### ISSUE TITLE
node controller

### ISSUE THREAD

**Issue by tyamamoto** [labrad/pylabrad#31]
In order to use the brower-based server controller, I started labradnode by doing
C:\Python27\Scripts\twistd.py -n labradnode, 
then I got an error message that "Could not flatten 'LABRADNODE' to _". 
Despite the error message, I could start the web controller. 
However, if I try to start any of gpib device servers, 
it remains "staring" forever and never becomes "started", 
although the server appears in the manager and seems properly working. 
I did not have this problem in my old setup with pylabrad of a previous version (0.92.1). 
Do you have any idea about this?

**Comment by creilly** [comment]
I've tracked down the flattening "LABRADNODE" issue to the message updating listeners to the server's "status" message which is sent after a call to refreshServers(). The list of server information tuples is not being parsed correctly I guess.

I imagine that the web interface subscribes to these update messages so is it important that this parsing error being corrected?

**Comment by maffoo** [comment]
@creilly, are you using the latest version of the node (e.g. from git master) or an old release version? I think this issue should be fixed (https://github.com/labrad/pylabrad/commit/d68b46889d0052379658ca9b3a98e1833bb3d6a4#diff-e9dcc2d0ea223930dd282273e5678163) but if you are still seeing it in master please file a new issue with as much detail of what you did as possible. Thanks!

**Comment by creilly** [comment]
@maffoo yup that solved it : )

**Comment by maffoo** [comment]
awesome!

**Comment by DanielSank** [comment]
Close this issue?

**Comment by maffoo** [comment]
It's already closed :)
