### ISSUE TITLE
Does travis run scalalabrad and test pylabrad servers?

### ISSUE THREAD

**Issue by jayich** [labrad/pylabrad#325]
@maffoo ,  from https://github.com/labrad/pylabrad/blob/master/.travis.yml it looks like pylabrad servers are launched on travis and tested.

I am interested in doing the same [here](https://github.com/CampbellGroup/common)

I am curious if there is a reason other than time that similar testing is not implemented in [martinisgroup/servers](https://github.com/martinisgroup/servers)

**Comment by maffoo** [comment]
You're correct that on travis we spin up a scalabrad manager as well as some python servers and test them. The main reason we haven't set up on the servers repo directly is that most of the servers there are for interfacing to hardware, so it's rather hard to set up automated tests in a sandboxed environment without that hardware. There are some exceptions for which automated tests would be useful, like the datavault, we just haven't set it up.

**Comment by jayich** [comment]
Besides following pylabrad's .travis.yml, and having the bash script [install-scalabrad.sh](https://github.com/labrad/pylabrad/blob/master/scripts/test/install-scalabrad.sh) is there anything else I should be aware of or need to setup scalabrad on travis for testing purposes?

@maffoo , thank you.

**Comment by maffoo** [comment]
@jayich, I don't _think_ so, but it seems like something always comes up when messing with the travis configuration, so you may find some issues. I generally turn on the "Build Branch Updates" option in travis for the repository so it will run tests on branches you push. Then you can make changes to the travis config on a branch, push the branch, watch the tests run, repeat until things are working, and finally merge to master.
