### ISSUE TITLE
__dir__ in client.py no longer returns a list in python 3

### ISSUE THREAD

**Issue by fanmingyu212** [labrad/pylabrad#355]
IPython tab complete no longer works with python 3.6. It worked previously in python 2.7. 
Calling the `list()` constructor on the `key()` generator in the following line solves the issue. https://github.com/labrad/pylabrad/blob/edce74b094333b3457719cf02001147d45e7c0e5/labrad/client.py#L242

Changed code so autocomplete work:
`return sorted(set(list(self._attrs.keys()) + list(self.__dict__.keys()) + dir(type(self))))`

**Comment by jayich** [comment]
@fanmingyu212 is this expected behavior, or is this a bug in our Pyton 3.6 code?
