### ISSUE TITLE
publish new version of labrad to pypi?

### ISSUE THREAD

**Issue by fanmingyu212** [labrad/pylabrad#362]
The latest version of pylabrad on pypi is v0.97.2 (published Jun 2017) as of 2019-05-08. There have been a few fixes for pylabrad since v0.97.2 was published, and some fixes are used in our lab every day (e.g. autocomplete in IPython with python 3). Would it be good to release a new version of pylabrad, so people can get the fixes using pip update?

**Comment by maffoo** [comment]
I've just pushed out a new version 0.98.0. Please give it a try!
