### ISSUE TITLE
Improve formatting of wavemeter numbers

### ISSUE THREAD

**Issue by cholliman** [labrad/pylabrad#366]
separate GHz/MHz i.e. go from 640.095858 -> 640.095 858.

**Comment by jayich** [comment]
@fanmingyu212 Craig and I discussed this briefly.  I think this will be awesome.  It will certainly help the D7 team in the short term.  I am not sure if this is a  change that we want to implement in common, or if we want this to start happening in pydux.  Your guys call there.
