### ISSUE TITLE
Saving multidimensional data to data vault

### ISSUE THREAD

**Issue by jayich** [labrad/pylabrad#39]
I have a large array, 492 x 656, that I would like to handle with data vault.  I don't think it is possible to do this cleanly at present. A lot of independent variables is not appealing.    I would be happy to start a branch to help work on extending the functionality of data vault to larger arrays. Thoughts and discussion about how to move forward would be much appreciated.  

label: enhancement

**Comment by jayich** [comment]
@ejeffrey , are there any updates along the lines of saving matrices with data vault?  It looks like a lot of work has been done.  I see several seemingly relevant branches on martinisgroup/servers.  It looks like hdf5 is a potential option.  If this issue should be closed and moved to martinisgroup/servers we can do that.

**Comment by maffoo** [comment]
yes, we should close this; @ejeffrey's new version of the datavault which adds extended data types and uses hdf5 for the backend storage is here: martinisgroup/servers#187.
