### ISSUE TITLE
Unable to Install pylabrad 0.98.2 with pip >= 24.1 Due to Invalid Metadata

### ISSUE THREAD

**Issue by amachino** [labrad/pylabrad#397]
## Issue Description
I encountered an issue while attempting to install pylabrad version `0.98.2` using pip version `24.1` or higher. The installation failed with the following warning:

```
WARNING: Ignoring version 0.98.2 of pylabrad since it has invalid metadata:
Requested pylabrad from https://files.pythonhosted.org/packages/05/5d/27ce3bdaa8f9dc3ff933dc451c6829d49f5e5ba7ecabb0d810dc93523641/pylabrad-0.98.2-py2.py3-none-any.whl has invalid metadata: .* suffix can only be used with `==` or `!=` operators
    pyOpenSSL (>=16.2.*)
               ~~~~~~~^
Please use pip<24.1 if you need to use this version.
```

This issue seems to be related to the metadata format of the package, which is not compatible with pip versions 24.1 and above. According to the warning, the use of the .* suffix in dependencies is causing the problem.

## Steps to Reproduce

1. Attempt to install pylabrad 0.98.2 using pip version 24.1 or higher.
2. Observe the warning about invalid metadata and the failure to install.

## Expected Behavior
The package installation should proceed without errors or warnings related to metadata format.

## Additional Context

- Python Version: 3.9.18
- Pip Version: 24.1.1
- Operating System: Ubuntu 20.04.6 LTS

## Workaround
As suggested by the warning, you can use pip versions earlier than 24.1 to install this specific version of pylabrad. Alternatively, consider using a different version of the package that does not have metadata issues.

**Comment by maffoo** [comment]
I've uploaded a new release [0.98.3](https://pypi.org/project/pylabrad/0.98.3/) which fixes the metadata and can be installed with pip 24.x.
