### ISSUE TITLE
counts unit

### ISSUE THREAD

**Issue by jayich** [labrad/pylabrad#46]
It would be helpful to include "counts" as a unit.  For example when working with a PMT it is nice to use kiloCounts/second, or sometimes you want to just save with the unit "counts", for the total counts obtained in an experiment.

<enhancement>

**Comment by ejeffrey** [comment]
Hi Andrew,

Check out PR #177, which addresses this issue.

**Comment by jayich** [comment]
This is great.  Thank you Evan.  I'll try out the custom_unit branch.
