### ISSUE TITLE
This repo should be moved to the labrad organization

### ISSUE THREAD

**Issue by DanielSank** [labrad/pylabrad#51]
'cuz, you know, it's public, and like whatever.

If I can get an aye aye from @ejeffrey @pomalley and @maffoo I will just do it.

**Comment by pomalley** [comment]
Sounds good. I guess we should move jlabrad and the Delphi stuff as well. What about servers?

**Comment by maffoo** [comment]
aye aye

**Comment by chrismacklin** [comment]
This would be helpful for us third-party users.  It might also be nice to split out quasi-core servers (gpib bus, gpib manager, etc.) from the martinisgroup servers repo to make it more clear to new labRAD users which servers are of general interest and which are more application-specific.  That would also be a good place for other labRAD users to be able to contribute servers of general interest to the community.

**Comment by DanielSank** [comment]
Yeah, the only reason we haven't done this is that we have to get everyone to freeze at the same time. We'll make a point of it.

**Comment by DanielSank** [comment]
So, anyone mind if I just do this

@maffoo @ejeffrey @pomalley @JulianSKelly

**Comment by pomalley** [comment]
well we'll have to update all the dataking computers, no? and really everyone's computer in the lab once they try to pull?

**Comment by DanielSank** [comment]
Just have to change what `origin` points to. No biggie.

**Comment by jwenner** [comment]
@DanielSank, seems like the issue should now be closed, right?
