### ISSUE TITLE
Update cheese shop

### ISSUE THREAD

**Issue by DanielSank** [labrad/pylabrad#82]
The version there is from 2010.
Also, can we make the creds for doing that somehow available to core devs?

**Comment by maffoo** [comment]
@DanielSank, if you create an account on PyPI and let me know the username I can give your account permission to upload to pylabrad.

**Comment by DanielSank** [comment]
It's danielsank.

Thanks.

**Comment by maffoo** [comment]
you are now added to the pylabrad package on pypi

**Comment by maffoo** [comment]
I guess this issue is about more than just getting access to pypi, we should see about updating the package that is there.

**Comment by jwenner** [comment]
Can we close this as pypi has now been updated?

**Comment by maffoo** [comment]
Closing as suggested by @jwenner now that we have the build scripts fixed up.
